### ISSUE TITLE
Crash after changing region

### ISSUE THREAD

**Issue by ricariel** [reinhard-brandstaedter/solarflow-statuspage#30]
Got connection errors when running in online mode:
[log](https://dpaste.org/y7D95/raw) 

After a while the container is unhealthy.

The Solarflow is visible in the zendure app and is working correct.  Region is EU. 
Environment Variables:
```bash
TRAEFIK_RULE=Host(`domain`)
ZEN_USER=user@email
ZEN_PASSWD=password
MQTT_HOST=ipofmqtt
ZEN_MQTT=mqtteu.zen-iot.com
COMMAND= --online
SF_DEVICE_ID=deviceid
SMARTMETER_TOPIC=/tele/
```

Snippet of compose file:
```yaml
version: '3.8'
services:
solarflow-dashboard:
image: rbrandstaedter/solarflow-statuspage:latest
command: ${COMMAND:-" --offline"}
restart: unless-stopped
environment:
- ZEN_USER=${ZEN_USER}
- ZEN_PASSWD=${ZEN_PASSWD}
- ZEN_MQTT=${ZEN_MQTT:-'mq.zen-iot.com'}
- MQTT_HOST=${MQTT_HOST}
- MQTT_USER=${MQTT_USER:-"none"}
- MQTT_PWD=${MQTT_PWD:-"none"}
- MQTT_PORT=${MQTT_PORT:-1883}
volumes:
- "/etc/timezone:/etc/timezone:ro"
- "/etc/localtime:/etc/localtime:ro"
networks:
- default
- docker_gwbridge
labels:
- traefik.enable=true
- traefik.http.routers.solarflow.entrypoints=websecure
- traefik.http.routers.solarflow.rule=${TRAEFIK_RULE}
- traefik.http.routers.solarflow.middlewares=localnet@file
- traefik.http.routers.solarflow.tls=true
- traefik.http.routers.solarflow.tls.certresolver=myresolver
- traefik.http.services.solarflow.loadbalancer.server.port=5000
- traefik.docker.network=docker_gwbridge

networks:
- default:
driver: bridge
driver_opts:
com.docker.network.driver.mtu: 1400
docker_gwbridge:
external: true
```
